<a href="https://colab.research.google.com/github/GeorgeMartin2021/Probability_Statistics/blob/main/Martinez_Lab_3HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loops

In [ ]:
for i in range(10): #for loop that counts to 10
    print(i) #prints the loop

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(3,9): #for loop that starts from 3 to 9
    print(i) #prints the loop

3
4
5
6
7
8


In [ ]:
for i in range(4): #for loop that counts from 0 to 4
    print("Test Number:", i) #prints the numbers with text

Test Number: 0
Test Number: 1
Test Number: 2
Test Number: 3


# Functions

In [ ]:
def square(x): #python function
    return x**2 #returning square

In [ ]:
square(5) #square of a number

25

In [ ]:
square(16) #squaring a number using the function as previous

256

In [ ]:
square(square(3)) #squaring the squaring function

81

In [ ]:
def add_two(x): #python functon
    return x+2 #the function will add + 2 to the number

In [ ]:
add_two(9) #adding + 2 to 9

11

In [ ]:
square(add_two(9)) #squaring the addition of + 2

121

# Branching

In [ ]:
choice = "apple" #stating that the choice is apple and it can now be used throughout the program

In [ ]:
if choice == "apple": #if the choice equals apple

    print("You choose apples.") #it will print this

else: #if it does not meet that condition,
    
    print("You did not choose apples.") #it will print this

You choose apples.


In [ ]:
choice = "orange" #now the choice is orange

In [ ]:
if choice == "apple": #if choice = apple

    print("You choose apples.") #it will print this

elif choice == "orange": #else if the choice equals orange

    print("You choose oranges.") #it will print this

else: #if it doesnt equal either, it will print below
    
    print("You did not choose apples or oranges.")

You choose oranges.


In [ ]:
if choice == "apple": #if the choice is apple

    print("You choose apples.") #it will print apple

else: #if the choice was not apple, it will print below
    
    print("You did not choose apples.")

You did not choose apples.


# User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #asking user input to then store in the variable 'choice'

Please enter your choice (i.e. apple): apple


In [ ]:
choice #stored variable of the user input

'apple'

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #asking user input to then store in the variable 'choice'

Please enter your choice (i.e. apple): oranges


In [ ]:
choice #stored variable of the user input

'oranges'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


# Cards


In [ ]:
import numpy as np #numpy library

In [ ]:
np.random.permutation(52) #permutating the array in a random order up to the number 52

array([38, 17, 26, 39, 43, 28,  9, 29, 33, 37, 36, 44, 10, 42, 34, 50, 45,
       40,  2, 16, 30, 13, 20,  6, 21, 48,  5, 11, 46,  3, 14,  1, 32, 25,
       19, 31, 24,  7, 49, 35, 27, 12, 47,  4, 41, 18, 22,  8, 51, 23,  0,
       15])

In [ ]:
cards = np.random.permutation(52) #storing the permutation in the variable cards

In [ ]:
cards #variable that we stored the permutation in

array([48, 49,  9, 12, 26, 36, 34,  6,  5, 23, 35, 22, 42, 10, 13, 25, 46,
       11, 31, 39,  0,  4, 44, 27, 32, 45, 43,  1, 30, 16, 19, 51, 18, 33,
       17, 14, 15, 20,  2, 38, 37, 28, 29,  3, 21, 24, 50,  7, 47, 41, 40,
        8])

In [ ]:
cards[0] #showing the first number in the array that we stored

48

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #setting the array in the correct order up to 52

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #same thing but with remainder 13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 #same thing but dividing by 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #character string and storing it in variable suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #character string and storing it in variable names

In [ ]:
suits #echoing back the character string stored in the variable

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
suits[0] #showing the first stored character in the variable array

'Clubs'

In [ ]:
names[1] #showing the second stored character in the variable array

'Two'

In [ ]:
def card_name(card_number): #python function
    
    suit = card_number//13 #storing the card number divided by 13 in the variable suit
    name = card_number%13 #storing the card number with the remainder 13 in the variable name

    return names[name] + " of " + suits[suit] #returning the character arrays via the variables & making a card deck with the function

In [ ]:
card_name(0) #showing this with the first stored characters in each array

'Ace of Clubs'

In [ ]:
card_name(51) #same as before but with the 51st stored character in each array

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) #setting the permutation in cards variable

In [ ]:
top_of_deck         = card_name(cards[0]) #making a separate variable to show the full name of the specific card in the array
second_card_in_deck = card_name(cards[1]) #making a separate variable to show the full name of the specific card in the array
last_card_in_deck   = card_name(cards[-1]) #making a separate variable to show the full name of the specific card in the array

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck #showing the results of the previous variable

('Queen of Clubs', 'Four of Diamonds', 'Two of Spades')

In [ ]:
for i in range(5): #for loop to show the first 5 results in the array
    print(card_name(cards[i])) #printing these results

Queen of Clubs
Four of Diamonds
Six of Clubs
Ace of Hearts
Jack of Spades


In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #tying the specific array we did before with a image URL to show the specific card
card_url_tail = ".png" #file type of the said image

In [ ]:
suit = ['k','p','s','l'] #setting the character array into a variable
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] #another character array set in a variable

In [ ]:
i = np.random.randint(4) #generating a random number between 0-3 in the array & storing it in i
j = np.random.randint(13) #generating a random number between 0-12 in the array & storing it in j

In [ ]:
i,j #showing the results of our previous stored variables

(1, 11)

In [ ]:
suit[i] #using the previous stored variable in our suit array

'p'

In [ ]:
card[j] #using the previous stored variable in our card array

'q'

In [ ]:
from IPython.core.display import display, HTML #python library to import HTML functionality via images

In [ ]:
def show_img(img): #python function to show an image via HTML
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i]+card[j] + card_url_tail #storing the image for a random suit in the card deck

In [ ]:
show_img(img) #displaying our results